name: tiger-habitat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - geopandas
  - shapely
  - rasterio
  - matplotlib
  - plotly
  - folium
  - pydeck
  - joblib
  - pyyaml
  - scipy
  - openpyxl
  - pip
  - pip:
      - streamlit
      - streamlit-folium
